services:
  ##############################
  #          [Nginx]          ##
  ##############################
  nginx:
    build:
      context: .docker/nginx
      args:
        USER: ${USER}
        TZ: ${TZ}
        WORKDIR_SERVER: /var/www/${NAMESPACE}
        SERVER_NAME: ${SERVER_NAME}
        SERVER_PATH: ${SERVER_PATH}
    container_name: ${NAMESPACE}_nginx
    working_dir: /var/www/${NAMESPACE}
    depends_on:
      - php
    ports:
      - ${WEBSERVER_SECURE_PORT}:443
      - ${WEBSERVER_UNSECURE_PORT}:80
    volumes:
      - ${PWD}:/var/www/${NAMESPACE}:delegated
      # [PHP]
      - php_socket:/var/run/php
    networks:
      - shared-network
      - default

  ###############################
  ##           [PHP]           ##
  ###############################
  php:
    build:
      context: .docker/php
      args:
        USER: ${USER}
        TZ: ${TZ}
        PHP_VERSION_SET_IMAGE: php:${PHP_VERSION_SET:-8.4}-fpm-alpine
        PHP_VERSION_SET: ${PHP_VERSION_SET:-8.4}
        WORKDIR_SERVER: /var/www/${NAMESPACE}
        XDEBUG_ENABLE: 1
    container_name: ${NAMESPACE}_php
    environment:
      PHP_IDE_CONFIG: "serverName=localhost"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /var/www/${NAMESPACE}
    volumes:
      - ${PWD}:/var/www/${NAMESPACE}:delegated
      - php_socket:/var/run/php:cached
      - ${PWD}/.docker/php/conf/extra/php-ini-overrides.ini:/usr/local/etc/php/conf.d/php-ini-overrides.ini
    networks:
      - shared-network
      - default
  ###############################
  ##         [Database]        ##
  ###############################
  database:
    build:
      context: .docker/SQL
    container_name: ${NAMESPACE}_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  ###############################
  ##         [MYSQL]         ##
  ###############################
  mysql_data:
  ###############################
  ##           [PHP]           ##
  ###############################
  php_socket:
    driver_opts:
      type: tmpfs
      device: tmpfs

networks:
  shared-network:
    name : shared-network
    external: true