services:
  ##############################
  #          [Nginx]          ##
  ##############################
  nginx:
    build:
      context: .docker/nginx
      args:
        USER: ${USER}
        TZ: ${TZ}
        WORKDIR_SERVER: /var/www/${NAMESPACE}
        SERVER_NAME: ${SERVER_NAME}
        SERVER_PATH: ${SERVER_PATH}
    container_name: ${NAMESPACE}_nginx
    working_dir: /var/www/${NAMESPACE}
    depends_on:
      - php
    ports:
      - ${WEBSERVER_SECURE_PORT}:443
      - ${WEBSERVER_UNSECURE_PORT}:80
    volumes:
      - php_socket:/var/run/php

  ###############################
  ##           [PHP]           ##
  ###############################
  php:
    build:
      context: .docker/php
      args:
        USER: ${USER}
        TZ: ${TZ}
        PHP_VERSION_SET_IMAGE: php:${PHP_VERSION_SET:-8.4}-fpm-alpine
        PHP_VERSION_SET: ${PHP_VERSION_SET:-8.4}
        WORKDIR_SERVER: /var/www/${NAMESPACE}
    container_name: ${NAMESPACE}_php
    working_dir: /var/www/${NAMESPACE}
    volumes:
      - php_socket:/var/run/php:cached

volumes:
  ###############################
  ##           [PHP]           ##
  ###############################
  php_socket:
    driver_opts:
      type: tmpfs
      device: tmpfs