name: main

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
      - main
concurrency:
  group: ci-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  security:
    uses: ./.github/workflows/security.yml
    secrets: inherit

  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit
    needs: security