name: Unit & Functional Tests

on:
  workflow_call:

jobs:
  build-tests:
    name: Unit & Functional Tests
    runs-on: ubuntu-latest
    container: node:latest
    services:
      database:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: pictionary
          ports: 3306:3306
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Configure Git safe directory
        run: git config --global --add safe.directory "${GITHUB_WORKSPACE}"
      - name: Copy env file
        run: cp .env.test .env
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.4
          coverage: xdebug
          ini-values: memory_limit=-1
          extensions: imagick, bcmath,mysql-client, mysqli, intl, pdo_mysql, pdo_pgsql, pgsql, opcache, gd, xsl, zip, soap, pcntl, sockets, gettext, xdebug
      - name: Composer install
        uses: ramsey/composer-install@v3
        with:
          composer-options: --profile --ignore-platform-reqs
      - name: Setup MySQL
        run: |
          apt-get update
          apt-get install --yes mysql-client
      - name: Create Database
        run: |
          php bin/console doctrine:database:create --env=test
          php bin/console doctrine:schema:update --env=test --force --complete || echo "No migrations found or schema update failed"
      - name: Setup Assets
        run: |
          npm install
          php bin/console importmap:install
          php bin/console asset-map:compile
      - name: Load fixtures
        run: php bin/console doctrine:fixtures:load --env=test --no-interaction
      - name: PHPUnit Tests
        run: php bin/phpunit tests/ --configuration phpunit.xml --coverage-cobertura ./coverage.xml
        env:
          XDEBUG_MODE: coverage
      - name: Code Coverage Analysis
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: true
          hide_complexity: false
          indicators: true
          output: both
          thresholds: '0 80'
      - name: Add Coverage Summary
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
